### PR TITLE
Fix META template

### PR DESCRIPTION
**Pull request by NathanReb**
The template for the META is incorrect and `findlib` was silently failing to parse it!

### CODE REVIEW

**Comment by NathanReb** [comment]
It would be nice to be able to pick up such mistakes in opam-overlays' CI as we have to be compatible with `findlib`.

**Comment by NathanReb** [comment]
Gentle ping to @avsm as I can't assign you as reviewer!

**Comment by avsm** [comment]
good catch!

**Comment by avsm** [comment]
What was the failure mode that let you spot it? This would be good in opam-overlays CI indeed.

**Comment by NathanReb** [comment]
I found it because I couldn't load ctypes in the top-level in realworldocaml/book `mdx` tests.

It was a bit tedious figuring this out as findlib doesn't report errors in the top-level.

**Pull request merged**
